on:
  push:
    tags:
      - '**'
  workflow_dispatch:

name: 'Build and deploy'

jobs:
  build:
    name: 'Build and deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install dependencies
        run: npm ci
      - name: Build bot
        run: |
          npm run build
          cp settings.json.example settings.json
      - name: Cleanup
        run: |
          npm run build
          find . -maxdepth 1 -name ".*" -not -name "." -not -name ".sequelizerc" -exec rm -rf {} \;
          rm -rf src tests settings.json.example tsconfig.json readme.md babel.config.js
      - name: Zip artifact
        run: |
          zip release.zip ./* -r    
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bot
          path: ./release.zip

  deploy-to-testing:
    name: Deploy to testing
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Testing
    needs: build

  deploy-to-production:
    name: Deploy to production
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Production
    needs: deploy-to-testing
