on:
  push:
    tags:
      - '**'
    branches:
      - 'feature/deploy'
  workflow_dispatch:

name: 'Build and deploy'

jobs:
  build:
    name: 'Build and deploy'
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2

      - name: Setup npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install dependencies
        run: npm ci
      - name: Build bot
        run: |
          npm run build
          find . -name . -o -prune -exec rm -rf -- {} +
          rm -rf src tests
      - name: deploy
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: .
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
