on:
  push:
    tags:
      - '**'
  workflow_dispatch:

name: 'Build and deploy'

jobs:
  build:
    name: 'Build and deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
            
      - name: Install dependencies
        run: npm ci

      - name: Build bot
        run: |
          npm run build
          cp settings.json.example settings.json

      - name: Cleanup
        run: |
          npm run build
          find . -maxdepth 1 -name ".*" -not -name "." -not -name ".sequelizerc" -exec rm -rf {} \;
          rm -rf src tests settings.json.example tsconfig.json readme.md babel.config.js

      - name: Zip artifact
        run: zip release.zip . -ry

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot
          path: ./release.zip

  deploy-to-testing:
    name: Deploy to testing
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'Testing'
    secrets: inherit

  deploy-to-production:
    name: Deploy to production
    needs: deploy-to-testing
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'Production'
    secrets: inherit
