on:
  push:
    tags:
      - '**'
  workflow_dispatch:

name: 'Build and deploy'

jobs:
  build:
    name: 'Build and deploy'
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2

      - name: Setup npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install dependencies
        run: npm ci
      - name: Build bot
        run: |
          npm run build
          cp settings.json.example settings.json
          sed -i 's/CLIENT_ID/${{ secrets.CLIENT_ID }}/g' settings.json
          sed -i 's/DISCORD_TOKEN/${{ secrets.DISCORD_TOKEN }}/g' settings.json
          sed -i 's/OPEN_DATA_TOKEN/${{ secrets.OPEN_DATA_TOKEN }}/g' settings.json
          sed -i 's/HEARTBEAT_URL/${{ secrets.HEARTBEAT_URL }}/g' settings.json
      - name: Cleanup
        run: |
          npm run build
          find . -maxdepth 1 -name ".*" -not -name "." -not -name ".sequelizerc" -exec rm -rf {} \;
          rm -rf src tests settings.json.example tsconfig.json readme.md babel.config.js
      - name: Deploy
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude kentekenbot.db
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
      - name: Post deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ${{ secrets.DEPLOY_PATH }}
            npx sequelize-cli db:migrate:status | grep -q 'down' && cd script && ./backup-db.sh && ../ && npx sequelize-cli db:migrate
            pm2 reload kentekenbot
