on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

name: Test and lint

jobs:
  build:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
      - name: Run linter
        run: npm run lint
